plugins {
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

sourceCompatibility = targetCompatibility = '17'

version = '1.0.0'
group = 'com.example.veritykiller'
archivesBaseName = 'VerityKiller'

minecraft {
    mappings channel: 'official', version: '1.20.1'
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.3.0'
}
