modLoader="javafml"
loaderVersion="[47,)"

[[mods]]
modId="veritykiller"
version="1.0.0"
displayName="Verity雷霆顶级宇宙超级无敌牛逼可拉屎无敌宇宙全球最强补丁"
authors="BeilinYao"
description="其实我也不知道在补丁什么但是你可以启动游戏试试看awa"
logoFile="icon.png"
license="MIT"
